name: Log, Build And Push

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_Password }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ivanspasov/springbootapi:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Set Context in K8s cluster
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
        id: setcontext

      - name: Deploy in k8s cluster
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: 'default'
          # Path to manifest files
          manifests: |
            Deployment.yaml
            Service.yaml
          images: 'ivanspasov/springbootapi:latest'